### ISSUE TITLE
Demo Displaying error instead of website

### ISSUE THREAD

**Issue by incredibleX** [ddimitrioglo/turbo-tribble#8]
The demo link you have added is displaying the following error:
`
Fatal error: You must enable the intl extension to use CakePHP. in /home/user6924/domains/turbo-tribble.ml/config/bootstrap.php on line 38`

Can you please fix the issue so that we can see the demo and use it in our projects?

**Comment by ddimitrioglo** [comment]
Hi,
thank you for your feedback, i'll fix it by tomorrow morning

**Comment by incredibleX** [comment]
Sure, I'm Looking forward to it. :+1:

**Comment by ddimitrioglo** [comment]
Fixed.
Thank you for waiting.

**Comment by incredibleX** [comment]
Thanks. You Rock :+1:
